---
title: Carbon Emissions of Top Emitting Countries
author: Jessica Forsstrom and Mariana Ahlquist 
output: github_document
date: "`r Sys.Date()`"
editor_options:
  chunk_output_type: console
---

<!-- Short Description  -->
This project is looking at the trends and total amounts of carbon emissions from countries around the world. Source data can be found in the bp Statistical World Energy Review of 2021.

*Updated on `r Sys.time()`*

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}

library(rmarkdown)

knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%"
)
```


## Table of contents
* [General info](#general-info)
  * [Analyses](#Analyses)
    * [To do list](#to-do-list)
      * [Contact](#contact)

## General info

This project aims to show the magnitude of carbon emissions comparatively between countries both over time and overall. 

## Analysis

* Finding which countries emit the most each carbon emissions each year, then looking at total emissions from 1965 to 2021 and finding the top 5 countries that emit the most carbon emissions. Lastly, looking at the trends of these top five countries over the time period.

## In progress

* Analyzing the trend between carbon emissions and primary energy consumption by country or region.

## To-do list

* Look at carbon emissions per capita and how that compares to total carbon emissions. Look at the relationship carbon emissions has with economic growth/output. Develop strategies to help mitigate the large amount of carbon being emitted by these large emitting countries. 

## Status
Project is: _in progress_

## Contact
Created by [Jessica Forsstrom, Marianna Ahlquist](website_URL)
